### PR TITLE
Dynamic scene output

### PR DESCRIPTION
**Pull request by alexyao2015**
fixes sleep and other apps #19

### CODE REVIEW

**Comment by alexyao2015** [comment]
This change is potentially breaking if the user had a config file that is broken. Ie has scenes existing attached to nonexistent groups

**Comment by mariusmotea** [comment]
I think your implementation will work but will not fix the config for bad lights assignment to scenes. I think the only way hue apps move the lights from groups is via PUT requests in scenes. We can add there a special function to sanitize the scenes config.

**Comment by mariusmotea** [comment]
"This branch has conflicts that must be resolved" please update the commit.

**Comment by alexyao2015** [comment]
Yeah that is the problem. I haven't tested it much but I can only hope that the config isn't bad. The other option would be the completely sanitize the config on startup or something (ok idea)? Or when the put function is run (probably a bad idea)?

**Comment by alexyao2015** [comment]
Don't merge this. It causes issues with routines. Need to fix them

**Comment by alexyao2015** [comment]
Ok I think its good now. I tested it but I know that it probably can be better, though it seems good for now.
@mariusmotea Can you take a look now?

**Comment by mariusmotea** [comment]
I'm not home. Tomorrow i will check.

**Comment by alexyao2015** [comment]
@mariusmotea Can you take a look at these pulls?

**Comment by mariusmotea** [comment]
Sure, sorry, i was very bussy this week with my printer upgrade

**Comment by mariusmotea** [comment]
Question, why you use copy command?

**Comment by alexyao2015** [comment]
Copy was used because that is the only way to reuse a dictionary. Other option was the use loop

**Comment by mariusmotea** [comment]
i used following sintax to iterate thru objects and also to change them during iteration:

`for scene in list(bridge_config["scenes"]):`

**Comment by alexyao2015** [comment]
Ok thats better. Good to merge?

**Comment by alexyao2015** [comment]
I think I misunderstood so are you saying to not use copy and just iterate over?

**Comment by alexyao2015** [comment]
Ok it seems good now?

**Comment by alexyao2015** [comment]
I've been running this for some time and it seems to work perfectly fine.

**Comment by alexyao2015** [comment]
Hmm really? I think you probably had something broken with your config.

**Pull request merged**
