### PR TITLE
Fix #566

### LINKED ISSUE #566: `is not` is deprecated in newer python versions
**Describe the bug**
New python version is expecting `!=` rather than `is not`. Is not is deprecated.

**Steps to Reproduce**
Normal diyhue startup.

**Expected behavior**
No error.

**Logs**
```
/opt/hue-emulator/functions/entertainment.py:97: SyntaxWarning: "is not" with a literal. Did you mean "!="?
  if len(nativeLights) is not 0:
/opt/hue-emulator/functions/entertainment.py:104: SyntaxWarning: "is not" with a literal. Did you mean "!="?
  if len(esphomeLights) is not 0:
/opt/hue-emulator/protocols/esphome.py:180: SyntaxWarning: "is not" with a literal. Did you mean "!="?
  if address["esphome_model"] is not "ESPHome-Toggle":
```

**Docker Info (please complete the following information):**
 - Architecture (Ex: x86, ARM): aarch64
 - Docker image version (Ex: latest, arm-05f043b, 128): diyhue Hassio Add-on
 - OS (Ex: Windows 10, Ubuntu Buster): Alpine
 - Hardware (Ex: PC, Raspberry Pi 1/2/3/Zero): Pi 4

**Checklist**
- [x] I confirm that this is a bug report
- [x] I confirm that I have completed this template to the best of my ability

**Additional context**

### PR DESCRIPTION
**Pull request by MaxBec**
Signed-off-by: Max Beckenbauer <max.bec92@gmail.com>

### CODE REVIEW

**Comment by alexyao2015** [comment]
Its a syntax error, but it still works for now. No need to merge this to master asap

**Comment by MaxBec** [comment]
> Its a syntax error, but it still works for now. No need to merge this to master asap

I see no reason to wait for this hotfix. Users get distracted by this.

**Review by mariusmotea — APPROVED** [review]
This is simple and safe

**Comment by juanesf** [comment]
https://github.com/juanesf/diyHue/commit/7e813205bd074a4532a00dd504bc90c0cdf4c33f

**Comment by MaxBec** [comment]
> [juanesf@7e81320](https://github.com/juanesf/diyHue/commit/7e813205bd074a4532a00dd504bc90c0cdf4c33f)

Thank you Juan. Will add the reusable port thing in another hotfix!

**Pull request merged**
