### PR TITLE
Support Shelly1 from Shelly

### PR DESCRIPTION
**Pull request by TheConway**
https://shelly.cloud/shelly1-open-source/

### CODE REVIEW

**Comment by mariusmotea** [comment]
This looks very nice, Thanks.

**Comment by Ro4cHii** [comment]
How can I add a Shelly1 to diyHue? 
I updated my diyHue Docker container to the latest available image but I am still not able to find any possibility to do so.

**Comment by Paalap** [comment]
Just search for new lights from the app, like for any other light

**Comment by Ro4cHii** [comment]
Thank you @Paalap!

I had to reset the Shelly to factory settings, add it via Hue Essentials and eventually configure it via the web interface to connect to my WiFi. Now it is working :)

**Comment by SaulGoodman1337** [comment]
Hi,
how about the Shelly dimmer. Is a simple integration possible here?

**Pull request merged**
