### PR TITLE
Remove coap-client binaries

### PR DESCRIPTION
**Pull request by 7FM**
Currently untested besides building the docker image.

### CODE REVIEW

**Comment by mariusmotea** [comment]
On what platform did you build the image?

**Comment by 7FM** [comment]
> On what platform did you build the image? Maybe I can test on the others.

Only on my laptop (x86_64). This would be great :)

**Comment by 7FM** [comment]
The CI seems to build the new docker images too, so at least building succeeds.

**Comment by 7FM** [comment]
Hm, when hitting the tradfri pair button with the new docker image, the following error message appears in the log: `EMRG coaps URI scheme not supported in this version of libcoap`.

**Comment by 7FM** [comment]
Apparently, `libcoap2-bin` is built without TLS support: `TLS Library: None`.
I also tried `libcoap-1-0-bin` this version, however, does not support the `-u` option.

**Comment by 7FM** [comment]
Got it, the package does provide `coap-client-gnutls` which should work!

**Comment by mariusmotea** [comment]
Hi. Is this ready to be merged?

**Comment by 7FM** [comment]
> Hi. Is this ready to be merged?

Yes

**Comment by mariusmotea** [comment]
Thanks for all your efforts .

**Pull request merged**
