### PR TITLE
not so elegant way to fix issue #19

### PR DESCRIPTION
**Pull request by PapACutA**
It is not really elegant but it schould fix issue #19 by not sending any scene details if sleep as android requests the config. So the app links and functions correctly. Maybe a usable hotfix until we find out what exact cause the problem.

### CODE REVIEW

**Comment by PapACutA** [comment]
I am not quite sure but every time i linked sleep as android with different diyHue installs i got this username and in the logs posted by Nostras in #19 it has the same username too. So i think sleep as android uses this username constantly.

**Comment by mariusmotea** [comment]
But if the scenes are empty the pair is working? I suspect some changes aplied to api that add some new values and are missing from bridge emulator.

**Comment by PapACutA** [comment]
The pairing it self was working all the time, the app freezes on getting the config. If the scenes are empty the connection is working an the app can control the lights as it was before.

**Comment by juanesf** [comment]
I have been using sleep as Android a long time ago with diyHue and without problems before starting the bridge search you have to press the link button

**Comment by PapACutA** [comment]
Ok i will try it. But i was using the app with the diyHue for about a year now without any problems. In this year i had almost the same light set up and updated the bridge only once last november/december, the last app update was mid of january. After that everything works just fine until i added a [generic on off device](https://github.com/diyhue/Lights/blob/master/Arduino/Generic_ON_OFF_device/Generic_ON_OFF_device.ino.) to my living room 2 weeks ago. Since then the app shows this behavior.
After doing some tests i found out that sleep as android works fine if it didn't get the scenes. That is why i wrote this workaround to fix this problem for now. Until we know what the real cause of the problem is.

**Comment by PapACutA** [comment]
> But this will not work because the username is random hash. Probably you pick the username from your config but on new pair it will be different.

@mariusmotea I digged a bit deeper in the HueEmulator3.py and now i know what you mean. At line 1664 it generates the hash. But when i test following line of code in python3 i get the same hash as my or nostras username of sleep as android. 
`hashlib.new('ripemd160', "S".encode('utf-8')).hexdigest()[:32]` results in `'4fada22cfb7cfc0a0b102ebd73cb1fad'`
Looks like the `post_dictionary["devicetype"][0]` equals just `"S"` is this right or is this maybe a bug too.

**Comment by mariusmotea** [comment]
I have an original bridge, i will check for differences. 100% the id of the scenes must be a hash ~10 characters, i always generate the id as string number. will try to fix this.

**Comment by PapACutA** [comment]
if it helps here are my actual scenes https://pastebin.com/jeZz7rEF

**Pull request closed without merging**
