### PR TITLE
hotfix wrong docker arch pull

### PR DESCRIPTION
**Pull request by Mevel**
hotfix for wrong arch pull docker image

### CODE REVIEW

**Comment by alexyao2015** [comment]
This won't work... It's a known docker bug (look though my commit history for the bug number). In fact, this will make things worse as you are modifying the base docker image that is applied to every architecture. I have it setup so it correctly pulls the correct architecture when building.

**Comment by Mevel** [comment]
the fix is not the buster or stable-slim base image. the actual fix is the removal of the lowercase "L" in the manifest annotation. Currently on RPI3 and 2 the docker pulls the wrong arch.

**Comment by alexyao2015** [comment]
Again, if you look through the commit history, you will find that I indeed had it that way previously and from multiple bug reports, that didn't work. In fact, I had to manually go an retag everything that way in an effort to fix it. The l at the end is in reference to a potential fix, which doesn't seem to work.

**Comment by alexyao2015** [comment]
Also, the changes to the dockerfile appear to be unnecessary as it should be handled by the base image. There also appears to be an apt-get update, which doesn't appear to be necessary.

**Comment by Mevel** [comment]
The big issue was the wrong pulled arch

> 
> 
> Also, the changes to the dockerfile appear to be unnecessary as it should be handled by the base image. There also appears to be an apt-get update, which doesn't appear to be necessary.

Thats correct the architecture is basically handled by the image it was for testing: adding armhf support natively

**Comment by alexyao2015** [comment]
Go ahead and merge if you wish to disregard my warnings.

**Comment by Mevel** [comment]
if you have another idea on how to fix the issue of Raspbian docker pulling the wrong image from docker hub i am all ears! glad you followed the PR

**Comment by alexyao2015** [comment]
> It's a known docker bug
There is no fix

**Comment by mariusmotea** [comment]
@alexyao2015 today we fight for a few hours with this bug. Too many users where not able to run entertainment effects so i made a test with a raspberry pi and i also was affected. It was good because i was able to test now. After many tests we conclude the issue is on client side that pull the wrong image arch, but this was happening only with diyhue image, not for example with buster-slim. Using the command `docker manifest inspect --verbose` i was able to see the manifests differences, and only noticiable difference was on the "platform" => "variant".

```  
                     "platform": {
                                "architecture": "arm",
                                "os": "linux",
                                "variant": "v6"
                        }
                },
  ```

**Comment by alexyao2015** [comment]
I've concluded the same thing a few months back. The issue ultimately led to a known Docker bug. There seems to be no way to fix Docker so it correctly pulls images from the manifest. If users want to use it, I suggest they simply manually pull the correct architecture, which is why individual architecture tags are still available.

**Comment by mariusmotea** [comment]
Test this fix, you will see it simply works. This was made after we read more about this issue, is a good workaround.

**Comment by alexyao2015** [comment]
I implemented this fix back in August after multiple bug reports. https://github.com/diyhue/diyHue/commit/6b117385ae0b53aafa26771fcd25acf60c3e9057

Ultimately reverting and reapplying the fix over the course of serveral months, leading me to the conclusion that there is simply no way to fix it. https://github.com/diyhue/diyHue/commit/25d837edb4daab254bacafc7331c7c51e26d93a8

**Comment by Mevel** [comment]
i found those articles quiet useful:

**Review by mariusmotea — APPROVED** [review]
Work on my Pi4 and Pi2

**Pull request merged**
