### PR TITLE
Scheduling not keeping up

### LINKED ISSUE #448: Scheduled action is not executed unless the scheduler thread evaluates it at a precise second when it has to be triggered
**Describe the bug**
I've found it when I wanted to  try out the "Hue Colorloop" formula in Hue app and discovered is not working.

**To Reproduce**
1. Open the Hue app
2. Click Explore->Hue labs
3. Scroll down to 'Browse all formulas' button and click it
4. Install the Hue Colorloop formula, you get the best chances of seeing the bug if you set the speed to "fast" (it schedules color change every second)

**Expected behavior**
Lights continuously transition between colors.

**Logs**
n/a

**Additional context**
So the formula is supposed to display a rainbow-like gradient on a light or a set of lights. How it does it under the hood:
1) It creates a sensor that, when triggered, transitions the color of the light (e.g. trigger - blue to purple, trigger once more - purple to red and so on):
```json
{
  "manufacturername": "Philips",
  "modelid": "HUELABSVTOGGLE",
  "name": "Living room and Bathroom, Vibran",
  "recycle": true,
  "state": {
    "lastupdated": "2020-08-23T16:14:47",
    "status": 1
  },
  "swversion": "2.0",
  "type": "CLIPGenericStatus",
  "uniqueid": "2:4:3f32-b468-42ca-9fef"
}
```
2) it creates a schedule that triggers this sensor via PUT method every N seconds:
```json
{
  "2": {
    "command": {
      "address": "/api/0/sensors/4/state",
      "body": {
        "status": 1
      },
      "method": "PUT"
    },
    "created": "2020-08-17T19:16:41",
    "description": "8:recurringTimer ",
    "localtime": "R/PT00:00:01",
    "name": "Hue colorloop",
    "recycle": true,
    "starttime": "2020-08-23T15:52:07",
    "status": "enabled",
    "time": "R/PT00:00:01"
  }
}
```
This is not working 100% of the time as the following happens (I traced it by running the emulator in debug mode locally):
- schedulerProcessor() thread is started and is executed every once in a while. Can be different depending on hardware, but it can be even less that once a second on slow computers (I'l running Docker on BeagleBone Black).
- line 504 in  HueEmulator3.py decides if the action scheduled should be triggered by comparing current time with start time minus interval:
```
if bridge_config["schedules"][schedule]["starttime"] == (datetime.utcnow() - d).replace(microsecond=0).isoformat():
```
If that happens later than the action is supposed to be triggered, the schedule never triggers again. Example: start time is 4:00:00, interval is one second (R/PT00:00:01). Scheduling breaks if the line above is called at 4:00:02 or any time after that.

### PR DESCRIPTION
**Pull request by panovvv**
Fix #448
I'm guessting `diyhue/core:latest` is built from the master branch right? That's why I'm asking to merge this into master - doing that will give us back a piece of functionality that rarely works as it stands, and pretty soon!

### CODE REVIEW

**Comment by alexyao2015** [comment]
Again for all new pulls please pull into master-refactor

**Comment by panovvv** [comment]
@alexyao2015   I've updated the comment but looks like it happened after you've closed the PR :-) 
The scheduling barely works in `diyhue/core:latest` Docker image. I'm not sure what the plans are for merging the `master-refactoring` branch, but I suspect it's not any time soon? This small PR fixes the scheduling, so I thought it would be better to have in the Docker image sooner than that - will you reconsider merging it to master?

**Comment by alexyao2015** [comment]
I would hope for the master branch to be on a feature freeze for now. As for usage, people may already begin using the new branch as all images are already being tested and pushed to docker hub and GitHub actions now. So while it may not be merged soon, it would push people to test the new version if they find things that don't work.

**Comment by panovvv** [comment]
Gotcha! I'll update my docker image to `diyhue/core:master-refactor` then, and continue to submit things I find into `master-refactor`.
As a side note, someone really should update [the docs](https://diyhue.readthedocs.io/en/latest/getting_started.html) to point out to both :latest and :master-refactor and explaining that :latest is frozen while :master-refactor is "bleeding edge". I can see how the current version can create a lot of confusion (or maybe the others are just smarter than me :D ).

**Comment by alexyao2015** [comment]
[We are always taking pulls!](https://github.com/diyhue/ReadTheDocs/pulls)

**Pull request closed without merging**
