### PR TITLE
Update for OpenWrt

### PR DESCRIPTION
**Pull request by juanesf**
The binaries for OpenWrt arm (32-bits) are still pending, as soon as I compile I will upload them.
The openwrt-i686 binary will be missing (looking for a way to compile)

### CODE REVIEW

**Comment by alexyao2015** [comment]
If I'm not mistaken, this looks to be nearly identical to #259

**Comment by juanesf** [comment]
Yes, it includes it, but I have made some changes and it is included in binary for OpenWrt x86_64, we will also soon add OpenWrt arm (32-bits) and aarch64 (arm-64bits) to the file.

**Comment by alexyao2015** [comment]
Well I mean we should only have one pull with the same fix. Either close #259 or this one?

**Comment by juanesf** [comment]
I am going to close that until I have compiled the OpenWrt arm and aarch64 binary since at the moment I have trouble running OpenWrt correctly on the boards to compile

**Comment by juanesf** [comment]
added binary Entertainment OpenWrt aarch64

**Pull request closed without merging**
