### PR TITLE
Color brightness fixes + merged commits from master

### PR DESCRIPTION
**Pull request by SilveIT**
MiBox, ESPHome protocols need testing

### CODE REVIEW

**Comment by SilveIT** [comment]
Check
https://diyhue.discourse.group/t/esphome-and-mibox-color-brightness/61/3

**Comment by mariusmotea** [comment]
Hi,

There are lot of lines that replace the end of the line characte(s). Are you editing the code from a windows editor? On some linux distros i saw python trow errors because of this.

**Comment by SilveIT** [comment]
I've used VSCode to change the code, the code was stored under WSL. Then it was copy-pasted into my repo folder which is located on windows file system. I also used Notepad++ to merge.

**Comment by SilveIT** [comment]
The problem is probably core.autocrlf option of Git.
image
I've changed it, now it's better?

**Comment by SilveIT** [comment]
Should be ok now.

**Comment by mariusmotea** [comment]
I think is better, only `def addTradfriOnOffSwitch(sensor_id, group_id):` remain with this problem. In Notepad++ you can use Edit -> EOL Conversion -> Unix (LF)

**Comment by SilveIT** [comment]
image
Are you sure? Notepad++ shows me it's already Unix.

**Comment by SilveIT** [comment]
image
Are you sure? Notepad++ shows me it's already Unix.

**Comment by mariusmotea** [comment]
Let's merge it and check if there are any issues. Maybe was wrong before and you fix it now to Unix format.

**Pull request merged**
