### PR TITLE
Breakdown of tradfri,deconz and webserver into seperate files. WIP

### PR DESCRIPTION
**Pull request by 0x47726567**
Moved the code for tradfri,deconz and webserver to modules/tradfri,modules/deconz and WebServer.py

### CODE REVIEW

**Comment by Mevel** [comment]
Do we need actions when someone is updating from existing installation?

**Comment by 0x47726567** [comment]
I don't think so as almost zero code was changed. It just was moved to other files and then imported to the main one. One exception is the WebServer as i spit the run function to runHTTP and run HTTPS but it should be fine(i have tested it).

**Comment by 0x47726567** [comment]
One thing i noticed is that addTradfriDimmer,addTradfriCtRemote and a couple of others do not get called. I assumed they aren't implemented yet and i can't test them.

**Comment by 0x47726567** [comment]
I will work on it a bit more to cleanup some mistakes....

**Comment by mariusmotea** [comment]
Waiting for your new PR. This is something i wanted to do long time ago.

**Comment by mariusmotea** [comment]
For Deconz websocket  may be little more complicated because you need to pass the global bridge_config and ddxstate dictionaries inside the class functions. You can take a look how i implement similar think in develop branch for mqtt class. I'm not really happy with my implementation but it works.

**Comment by 0x47726567** [comment]
I want to spend some time on time as i want it to be stable. I don't want to risk breaking current setups.

**Comment by 0x47726567** [comment]
Generally, the global bridge_config needs to be passed to most of the modules so some code changes need to occur.

**Pull request closed without merging**
