### PR TITLE
Mi hub protocol

### PR DESCRIPTION
**Pull request by jespertheend**
I'll add documentation to https://github.com/diyhue/ReadTheDocs later on how to configure this. But basically if you add a light to the config file like this you should be good to go:

```
"lights_address": {
    "1": {
        "protocol": "mi_box",
        "group": 1,
        "ip": "192.168.1.5",
        "port": 5987,
        "light_type": "rgbww"
    }
}

```
Group is the group you linked with in the Mi-Light app. The ip depends on what ip your WiFi box has, probably best to look for connected devices in your router panel. And port I think is always 5987.
I believe it is possible to have different light types though I only own the rgbww type so I'm not sure if others work. But it might support "rgbw" and "hub" also. I took most protocol info of other light types from here https://github.com/domoticz/domoticz/blob/development/hardware/Limitless.cpp

### CODE REVIEW

**Comment by mariusmotea** [comment]
Thank you for support

**Comment by david-strauss-privoro** [comment]
Hi all, so how do I get this working with a new diyHue install?

**Comment by jespertheend** [comment]
@david-strauss-privoro you need to edit the diyHue config manually and restart diyHue.

**Comment by Kraechtshammer** [comment]
@jespertheend Hey, so I'm trying to set up my mi box using your protocol, but I can't really get it to work due to there being so few documentation (or did I miss something?) I have RGBCCT GU10 lamps which I want to setup... Which light type should I use for that? RGBW and RGBWW are just for white and warm white, after all... At least officially. Also, just adding those lines you posted above to the config results in diyHue not starting anymore, maybe there is more that I need to set up? I used docker for my installation. Please send help!

**Comment by jespertheend** [comment]
@Kraechtshammer phew it's been quite some time since I worked on this. I don't use this myself anymore since I have moved to https://github.com/sidoh/esp8266_milight_hub since it's a lot more stable. But I'll try to help.
Are you getting any error messages from diyHue when you add those lines?
I think you need RGBWW. RGBCCT GU10 is the one with rgb and two white temperature leds right? That's the one I have.

**Pull request merged**
