### PR TITLE
strftime("%s") is not portable

### PR DESCRIPTION
**Pull request by sebastianhaba**
Replaced strftime("%s") with timestamp(). Now it's more portable (fix for windows).

### CODE REVIEW

**Comment by alexyao2015** [comment]
Umm use docker? Strftime will be required to fix #240 so I'm going to say to not merge this.

**Comment by sebastianhaba** [comment]
Hmm, strftime("%s") is not officialy supported in python. It's a hack. Probably %s is passed to native system command. timestamp is officialy supported in python.

> Why you should not use datetime.strftime('%s')

Python doesn't actually support %s as an argument to strftime (if you check at http://docs.python.org/library/datetime.html#strftime-and-strptime-behavior it's not in the list), the only reason it's working is because Python is passing the information to your system's strftime, which uses your local timezone.

[Strftime and epoch](https://stackoverflow.com/questions/11743019/convert-python-datetime-to-epoch-with-strftime)

But ok it's your project :)

**Comment by alexyao2015** [comment]
Hmm well maybe it's worth looking into then. I'll do some more research

**Comment by alexyao2015** [comment]
So strftime is fine in general though? I just don't want to conflict with future fixes and basically invalidate this entire pull.

**Comment by sebastianhaba** [comment]
In general yes. Sfrtime with %s will return epoch time as long as is supported by sftrime in os (unix). In windows is not supported so exception is thrown. So you can't for example link bridge because you can't emultate link button. Timestamp function should works on all system with python 3.3+ installed. For example I checked timestamp on my assus router with custom merlin software (python 3.7.4) and It's works.

**Comment by alexyao2015** [comment]
Alright, I agree that something needs to be done about this. It wasn't originally my code, so I didn't realize that you meant "%s" was the issue. I thought you meant that strftime was the issue. In that case, I'll review and test this just to make sure and make sure we caught all occurrences of it.

**Pull request merged**
