### PR TITLE
ESPHome Protocol

### PR DESCRIPTION
**Pull request by alexyao2015**
Here is sample esphome code for rgbw to make this work. 
```
esphome:
  name: light1
  platform: ESP8266
  board: esp01_1m

ota:
  password: "redacted"
    
wifi:
  ssid: "redacted"
  password: "redacted"
  
  ap:
   ssid: "ESPhome light1"
  
# Enable logging
logger:
  level: DEBUG

# Enable Home Assistant API
api:
  password: "redacted"

power_supply:
  - id: 'fast_led_pwr'
    pin: GPIO13

output:
  - platform: esp8266_pwm
    pin: GPIO5
    id: cold_white_gpio
    frequency: 4000 Hz
    inverted: False
    min_power: 0
    max_power: 1
    
  - platform: esp8266_pwm
    pin: GPIO12
    id: warm_white_gpio
    frequency: 4000 Hz
    inverted: False
    min_power: 0
    max_power: 1
    
light:
  - platform: cwww
    id: white_led
    name: "white_led"
    cold_white: cold_white_gpio
    warm_white: warm_white_gpio
    cold_white_color_temperature: 6500 K
    warm_white_color_temperature: 2000 K
    gamma_correct: 0.8
    default_transition_length: 0.4s

  - platform: fastled_spi
    id: color_led
    chipset: SM16716
    data_pin: GPIO14
    clock_pin: GPIO4
    power_supply: fast_led_pwr
    num_leds: 1
    rgb_order: BGR
    name: "color_led"
    default_transition_length: 0.4s
    gamma_correct: 0.8
    effects:
      - random:
          name: Random Effect With Custom Values
          transition_length: 5s
          update_interval: 3s

text_sensor:
  - platform: template
    name: "light_id"
    id: light_id
    lambda: |-
      return {"esphome_diyhue_light;mac_address;light_name;ct_boost;rgb_boost"};
    update_interval: 24h
    
switch:
  - platform: template
    name: alert
    id: alert
    optimistic: true
    turn_on_action:
      - light.turn_off: color_led
      - light.turn_on:
          id: white_led
          brightness: 100%
          color_temperature: 4000 K
      - delay: 1s
      - light.turn_on:
          id: white_led
          brightness: 10%
          color_temperature: 4000 K
      - delay: 1s
      - light.turn_on:
          id: white_led
          brightness: 100%
          color_temperature: 4000 K
      - delay: 1s
      - light.turn_on:
          id: white_led
          brightness: 10%
          color_temperature: 4000 K
      - delay: 1s
      - light.turn_on:
          id: white_led
          brightness: 100%
          color_temperature: 4000 K
      - switch.turn_off: alert
          
web_server:
  port: 80
```

Important notes: 

This supports all types of bulbs, rgbw, ct, rgb, dimmable, toggle

Automatic detection should work if the lights are named color_led, white_led, dimmable_led, toggle_led.

The text sensor must exist to allow for proper detection (replace the mac address with the actual mac address, replace ct and rgb_boost with numbers on how much to boost the brightness values (put 0 if none). Do not place any spaces between ";"

     Do not touch                mac            name in hue    ct         rgb
{"esphome_diyhue_light;mac_address;light_name;ct_boost;rgb_boost"}

### CODE REVIEW

**Comment by alexyao2015** [comment]
Entertainment seems to still have some weird issues with colors not changing fast enough. Not sure if its an issue with this particular protocol or something bigger.

**Comment by mariusmotea** [comment]
I cannot test this, but looks good.

**Comment by RomeyRome206** [comment]
Am I mistaking, or is there currently no way to get this to work with segmented ws2811/12 strips via ESPHome?

**Comment by alexyao2015** [comment]
You would be correct in that regard. That has not been implemented.

**Comment by mawa85** [comment]
So ESPHome does support partitioning (see: https://esphome.io/components/light/partition.html)
But if I understood correctly this is not working with DIYHue?

So 1 Strip = 1 Light?

**Comment by alexyao2015** [comment]
That is correct.

**Pull request merged**
