### PR TITLE
Build and tag image for beta and develop

### PR DESCRIPTION
**Pull request by maxcanna**
This way we could have `beta` and `develop` docker image too

### CODE REVIEW

**Comment by mariusmotea** [comment]
Thanks.

**Comment by alexyao2015** [comment]
Few problems. That commit was merged to master so it won't affect those two branches. Also, beta and develop have been pretty much abandoned. Master-refactor is the new branch.

**Comment by maxcanna** [comment]
It won't affect the two branches since they're behind `master`. A rebase it's enough to fix it 😉 
I enabled `beta` and `develop` after talking with @mariusmotea

**Comment by alexyao2015** [comment]
I had them building before with Travis but it seemed like it had been disabled with the switch to GitHub actions. I've never bothered to reenable them since because they had been abandoned...

**Pull request merged**
