### PR TITLE
Fix dynamic http_port in ssdp

### PR DESCRIPTION
**Pull request by memen45**
Default port number of 80 was hardcoded in ssdpBroadcast and Search, as well as in description.xml. With this pull request, this is fixed. The port number is filled in correctly according to the option --http_port

Now the bridge shows up correctly in Windows Network Devices as well, pointing to the webpage with the correct port number.

### CODE REVIEW

**Comment by mariusmotea** [comment]
But the port is not present in Hue API and it is fixed port to 80/443 as the Hue Bridge is embedded device and will always have these ports free. Will the hue apps run is the bridge is on a different port?

**Comment by memen45** [comment]
It does not work for all apps, I tried to connect the following:
- HueManic: does see it, but cannot connect to it when port is not 80
- Sleep As Android: same developer as Huemanic, excatly the same problem, does see it, but only connects if port is 80
- Hue Essentials: auto detect seems broken, but manual connect works on any port.
- Windows Explorer > Network: shows Philips hue now, double click links correctly to the http://ip:port/index.html

Note that the --http_port option was already there working, but the broadcast was not correct.

**Comment by alexyao2015** [comment]
So whats the point of this then if it has to be 80 anyways for applications to pair? It shows up fine in windows explorer without this?

**Comment by mariusmotea** [comment]
Something is wrong. "Travis CI - Pull Request Failing after 8m — Build Failed"

**Comment by memen45** [comment]
In the normal case: yes you are right!
However, if you run for example
`/opt/hue-emulator/Hue-emulator.py --http-port=8100`
The emulated bridge is indeed accessible through http://ip:8100/, however, the broadcast says always http://ip:80. That is what I tried to fix in this pull request: just aligning the broadcast with the actual port that is used in the code. 

Why using another port than default 80? I already have a webserver running on the same machine, so port 80 is already in use. Some apps require port 80 for the bridge (as listed above, and according to Google, Google Assistant and Alexa also require port 80), but some apps do not require this, so it is perfect to use hue-emulator alongside a running webserver with some apps.

**Comment by memen45** [comment]
Ah okay, I understand. I fixed it in the latest commit!

**Comment by alexyao2015** [comment]
@mariusmotea I think the build failing was because Travis was having issues. The logs showed the vm not having internet access.

**Comment by alexyao2015** [comment]
The commit would break the emulator completely right now. You need to pull in the port through args or environmental variables and define a default as 80. There is no default and there is no way to set the port now.

**Comment by alexyao2015** [comment]
Interesting. It looks like this feature already existed but just wasn't implemented properly

**Comment by mariusmotea** [comment]
Now it looks good.

**Pull request merged**
