### PR TITLE
Adding Support for Special Characters in Room Names

### PR DESCRIPTION
**Pull request by n3PH1lim**
I added a fix wich allow to use Special Characters in Room Names.

Tested with some weird things :-D

img_0270

Please check if this breaks something else.

Nothing found all is working normal incl. Entertainment

### CODE REVIEW

**Comment by n3PH1lim** [comment]
Sorry for the mess in the commits. I need more practice with Github.

**Comment by mariusmotea** [comment]
Perfect, thanks

**Comment by cheesemarathon** [comment]
Thank you for this fix. It has been a long outstanding bug. I updated the original issue over at the old repo in case anyone was still watching it.

**Comment by n3PH1lim** [comment]
Hi thanks it is my plesure that i can help at this awesome project. I hope this fix does does not breake something else.

**Pull request merged**
