### PR TITLE
Pass Deconz IP as env variables

### PR DESCRIPTION
**Pull request by WhistleMaster**
Related to #122 to be able to pass Deconz IP as an environment variable with Docker.

### CODE REVIEW

**Comment by mariusmotea** [comment]
Hi,

For some reasons the compilation of this pull request fail. Do you have tabs instead of spaces?

**Comment by WhistleMaster** [comment]
Yes I do, that’s the issue I guess. I’ll fix that as soon as possible. Thanks !

**Comment by WhistleMaster** [comment]
I've checked in the code and I don't have any tabs in the file I've modified. I don't know what's wrong with this PR.

**Comment by mariusmotea** [comment]
I will merge this because i believe the error is a timeout on accessing python repository

> No output has been received in the last 10m0s, this potentially indicates a stalled build or something wrong with the build itself.
> Check the details on how to adjust your build configuration on: https://docs.travis-ci.com/user/common-build-problems/#Build-times-out-because-no-output-was-received

**Comment by WhistleMaster** [comment]
Thanks ! How often is the Docker version (https://hub.docker.com/r/diyhue/core/) refreshed ? I tried to use the latest tag, but I don't see the modifications from the PR.

**Comment by cheesemarathon** [comment]
Looks like something has gone a bit funky with the latest tag. I'll look into it. Your pr was built though. If you look at the docker tags there are two with the git hash of your pr.

**Comment by WhistleMaster** [comment]
You're right, thanks !

**Comment by cheesemarathon** [comment]
Build errors have been fixed!

**Pull request merged**
