### PR TITLE
Update scripts and version

### PR DESCRIPTION
**Pull request by juanesf**
- Rename OpenWrt service script.
- Add zeroconf to OpenWrt using pip3 (WLED dependency).
- Update installation scripts, quick installation, and OpenWrt updater.
- Update diyHue software version to 1941132080
- Add zeroconf installation to host scripts
- Add install script for dev branch

### CODE REVIEW

**Review by juanesf — COMMENTED** [review]
[log-zeroconf.txt](https://github.com/diyhue/diyHue/files/5742655/log-zeroconf.txt)

**Review by juanesf — COMMENTED** [review]
https://github.com/diyhue/ReadTheDocs/pull/27

**Review by mariusmotea — COMMENTED** [review]
Can you confirm Hue Sync is working after these changes?

**Comment by juanesf** [comment]
Voy a hacer pruebas antes y después tanto en OpenWrt como Ubuntu con host script. Luego te comento como me va

**Comment by mariusmotea** [comment]
Hue Sync stop working with api version 1.41.0 and sw 1941132080, but maybe if we update just swversion it will still work

**Review by juanesf — COMMENTED** [review]
Obtained from: https://www.reddit.com/r/Hue/comments/jfhgb3/where_can_i_download_previous_versions_of_hue_sync/

**Comment by juanesf** [comment]
@mariusmotea 
According to the following link and some tests done, updating HueSync (pc) to version 1.5.x has problems connecting to the bridge. With this Hue App (Android) does not limit or ask to update the bridge.

**Comment by mariusmotea** [comment]
I'm working for a fix on this problem. Basically i need to implement a new protocol.

**Pull request closed without merging**
