### PR TITLE
Implementation of Yeelight Music Mode

### PR DESCRIPTION
**Pull request by SilveIT**
Yeelight now supports Philips Entertainment API
* Changed entertainment service method to pass Host IP argument;
* Changed sendLightRequest method to pass entertainment Host IP to turn on music mode on yeelight devices before sending them any commands;
+ Implemented YeelightConnection class which is now used to communicate with Yeelight devices and to maintain Yeelight Music Mode connections;
+ Implemented dictionary logic to support dedicated yeelight connections;

### CODE REVIEW

**Comment by SilveIT** [comment]
Never used Python before. There may be small mistakes. This should close #327.

Also, check line 61 of entertainment.py. While cycle on line 64 looks weird...

**Comment by mariusmotea** [comment]
Thanks for your work. At line 61 clearly there is a bug. As no entertainment application at that time used CIE color mode there was no test done. Please give me some time to analyse your implementation.
With how many bulbs you tested?

**Comment by SilveIT** [comment]
I've only tested it with one bulb. It works fine. It can also reconnect on connection problems. I think it'll work with any number of bulbs, because it uses dictionary (one per python thread, I don't want to mess with cross-thread stuff) to store connections. But if anyone can test it with multiple bulbs, it would be great.

**Comment by SilveIT** [comment]
Also, I don't know why, but the white color from HueSync is slightly pink on Yeelight. It is quite possible that there is a problem with color conversion.

**Comment by alexyao2015** [comment]
Nice, I'll take a look at it. You're likely right about the pink issue being due to color conversion. If you look at #181, you'll see the issue.

**Comment by alexyao2015** [comment]
Moved to #331

**Pull request closed without merging**
